# -----------------------------------------------------------------------------
# dev environment values.
#
# Committed on purpose: none of this is secret. Credentials come from ADC or
# OIDC, and the database password is generated by Terraform and stored in
# Secret Manager - it is never written here.
#
# REQUIRED: replace project_id with your own GCP project before applying.
# -----------------------------------------------------------------------------

project_id   = "REPLACE_ME-dev"
project_name = "tfs"
region       = "us-west1"

# --- Cost posture ------------------------------------------------------------
# Scale to zero: an idle dev environment costs nothing beyond registry
# storage. The trade-off is a cold start (~1-3s) on the first request.
backend_min_instances  = 0
backend_max_instances  = 3
frontend_min_instances = 0
frontend_max_instances = 3

backend_cpu     = "1"
backend_memory  = "512Mi"
frontend_cpu    = "1"
frontend_memory = "512Mi"

# --- Database ----------------------------------------------------------------
# Off by default. Cloud SQL has no free tier (~$8/month at db-f1-micro even
# when idle), and the backend runs fine without it: /health and
# /api/v1/hello work, /api/v1/items returns 503.
#
# To turn it on: set this to true and re-apply. Expect ~10 minutes for the
# VPC peering and instance creation.
enable_database              = false
database_tier                = "db-f1-micro"
database_availability_type   = "ZONAL"
database_disk_size_gb        = 10
database_backup_enabled      = true
database_deletion_protection = false

# --- Access ------------------------------------------------------------------
backend_public = true

# Lets a frontend running on your laptop (`npm run dev`) call the deployed dev
# backend directly. Not needed for the deployed frontend, which proxies
# browser traffic through its own origin.
additional_cors_origins = ["http://localhost:3000"]

log_level = "DEBUG"

# Dev should be disposable.
service_deletion_protection = false
